# Generated by Django 2.1.7 on 2019-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.EmailField(max_length=30)),
            ],
        ),
    ]
