# Generated by Django 2.1.7 on 2019-02-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190218_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('manager', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=256)),
                ('item_quantity', models.IntegerField()),
                ('item_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('status', models.CharField(max_length=256)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='main_app.SiteUser')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='main_app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('ship_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='main_app.Fleet')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='main_app.Ship'),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='main_app.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_name', 'parent')},
        ),
    ]
